######################################################################
#
# CISC 4080 (Computer Algorithms)
# Spring, 2018
#
# Project 3: Topological Sorting
#
# This is the Makefile
#
# Author: A. G. Werschulz
# Date:   16 Feb 2018
#
######################################################################

# add -g if you want to use a debugger
CXXFLAGS=-Wall -std=c++1z

proj3: proj3.o
	$(CXX) $(CXXFLAGS) -o proj3 proj3.o 

clean:
	@/bin/rm -f *~ \#*\# core* proj3 *.o


