######################################################################
#
# Chain matrix multiplication
#
# Author: Abadali Sheikh
# Date:   8 Mar 2018
#
######################################################################

# Add the -g flag to the end of this line if you want to use the
# debugger 
CXXFLAGS=-Wall -std=c++17 

proj4: proj4.o
	$(CXX) $(CXXFLAGS) -o proj4 proj4.o 

clean:
	/bin/rm -f *~ \#*\# core* proj4 *.o


